### ISSUE TITLE
Attributes Exposed in Templates Without Having to Reference the Attributes Hash

### ISSUE THREAD

**Issue by shanebo** [desiringgod/components-rails#13]
Instead of having to call on the attributes hash to access attributes, I propose we expose all attributes to the template. So instead of _having_ to do:

`<h1><%= attributes[:foo] %></h1>`

I propose:

`<h1><%= foo %></h1>`

But I also propose we expose the attributes hash for when we need access to it for other reasons. So the idea would be we'd use the attribute names as much as possible but call on the `attributes` hash if/when needed.

Some may say this feels like magic, but because components are scoped and it's easy to see what's exposed to the template, I think this is good clean fun — a removal of needless redundancy.

**Comment by scottcorgan** [comment]
@shanebo  So this is worth discussion together as @joeosburn-desiringgod and I have quite a bit (when I was up at HQ last).

This is because of a request I made. I won't die on this mountain, but I'm going to advocate to keep it for one main reason:

If we see code like `<h1><%= foo %></h1>`, there are 4 potential places this could come from

1. It's a component
2. It's a attribute
3. It's a local helper method
4. It's a global helper method

That's cray-cray to me! That's like the cascade in CSS. Do attributes override local helpers. Do local helpers override global helpers? It can become a mess, just like CSS.

In our attempt to chip away at developer cognitive load, I'm _highly_ recommending we error on being declarative rather than implicit here. Something I feel is very helpful is knowing exactly where your values come from. In an isolated incident, it doesn't seem to do much, but over a day, a week, and so on, we start to see the ability to navigate our code with both unhibited confidence and new-eyes-friendly clues.

I do believe the benefit we gain _scoping_ these property/method names outweighs the benefit we gain from making it look a little less verbose.

**Comment by benhutton** [comment]
@scottcorgan if we follow this logic, why not use a similar interface for components? Why let components be helper methods but not attributes?

**Comment by scottcorgan** [comment]
I'm ok with that. I don't think I was a part of that conversation. If I was, then I was wrong. I think the hardest part of rails for me is that helper methods are just magically available.

**Comment by shanebo** [comment]
Vote: Make attributes accessible in the template without referencing the parent hash so that you could access `<%= attributes[:foo] %>` using `<%= foo %>` instead.

**Comment by benhutton** [comment]
@scottcorgan you know, as I think about this more, I think you might be making this more confusing than it needs to be....

My guess is that attributes and local helper methods will not usually take parameters and have variable-ish names. Components will take parameters and have variable-ish names. Global helper methods will take parameters and have method-ish names.

Get the names right, and it will probably sort itself out for the most part :).

**Comment by shanebo** [comment]
Let's just all vote on it so we see where we're all at. Then we can go from there...

**Comment by joeosburn-desiringgod** [comment]
My vote is make attributes available as `attributes` hash, i.e, in the case of:
```
<%= abc(option1: 'value') %>
```
You'd access it in the template this way:
```
<%= attributes(:option1) %>
```

If you want to make it accessible via the word "option1", you'd write a helper method exposing it. If we want to add shortcut helper methods, we can do that via an option (perhaps even make it a default) via the "option/attribute" api that is being worked out in this PR: https://github.com/desiringgod/components-rails/pull/10

**Comment by scottcorgan** [comment]
@benhutton that may be so, but I was only trying to relay ideas in from all the FE frameworks. Here is an example of how a react component works:

```js
import React from 'react';
import globalHelper from './global-helper';

class MyComponent extends React.Component {

  // This is equivalent to our `show` method
  render() {

    return div({}, [

      // This is equivalent to "attributes"
      this.props.someValue,

      // This really has no equivalent in our component system, but it's the 
      // state that is local to the component only, and it can change at any time.
      this.state.someChangingState,

      // This is equivialent to our local helper methods
      this.someHelper(),

      // This is equivalent to our global helpers
      globalHelper()
    ])
  }
}

// Here's how it's used, kind of

MyComponent({someValue: 'some value'});
```

So, with that said, I'm open for anything that makes our jobs easier, I would just prefer to error on be declarative rather than concise.

**Comment by benhutton** [comment]
@joeosburn-desiringgod do you want `attributes(:option1)` or `attributes[:option1]`?

**Comment by joeosburn-desiringgod** [comment]
@benhutton Sorry, `attributes[:option1]`. That was a typo. I'll fix in the previous comment for clarity.

**Comment by shanebo** [comment]
The frameworks I've used to render views/templates (rails, express, etc.) makes the data/hash properties/keys available directly. That doesn't strike me as anti-declarative or magical, especially when we know that the only accessible data is what's set or passed into a component.

It seems like the point of difference stems from functional vs object oriented and declarative vs implicit. Shouldn't we settle the paradigm differences so we're not trying to mix oil and water on every PR where this comes up?

**Comment by benhutton** [comment]
Okay here's a crazy idea: let's get rid of this altogether. No attributes. Only helper methods, in the sense that you have to explicitly declare an attribute a helper to get access to it in the view. Then you don't have any ambiguity about whether it's a helper or not — they're all helpers! And any attributes that aren't declared as helpers are just knobs to configure other helper methods — they're not passed into the view.

**Comment by joeosburn-desiringgod** [comment]
@benhutton I'm good with that. 👍

**Comment by shanebo** [comment]
@benhutton me likes. Can we make component rails meta-program those helper methods for us, so we don't have to?

/cc @joeosburn-desiringgod @scottcorgan

**Comment by benhutton** [comment]
@shanebo @joeosburn-desiringgod @scottcorgan I would just add a `helper: true` option on `attribute`.

`attribute :foo, required: true, helper: true`

**Comment by joeosburn-desiringgod** [comment]
@benhutton I agree. What do you think about making `helper: true` the default, though (i.e. you have to say `helper: false` if you don't want a helper method?)

**Comment by shanebo** [comment]
@joeosburn-desiringgod _my_ initial opinion is that defaulting to required is kind of odd...

**Comment by benhutton** [comment]
@joeosburn-desiringgod i'm not sure about that....

If it defaults to `false`, then your reason for marking it `true` is to explicitly signal that this is part of the public API rather than just an internal knob. And you would have to do it if you wanted to use it at all.

If it defaults to `true`, then your reason for marking it `false` is to explicitly signal that this is NOT part of the public API and is just an internal knob. But you would never _have_ to do it. Our entire codebase could never mark anything as `false` and it would probably work just fine.

THUS, I'm not sure how useful this will be if we default to `true`. Might as well not include the knob at all.

Also, I'm not 100% sure that it would solve the problem that @scottcorgan is raising, as this then functionally looks exactly like what he was objecting to.

**Comment by scottcorgan** [comment]
wherever we end up I think these are the important things

- It's easy to find out which attributes must be given to the component for these reasons
  - Gives me explicit instructions when I fail to use the component correctly
  - Self documenting components in an easy to find location
- Find out which attributes are optionally available to tweak the component for these reasons
  - Self documenting components (easy to find out if I have options) in an easy to find location

**Comment by shanebo** [comment]
Okay let's take a vote to see where we're at...

**Comment by shanebo** [comment]
Vote: attributes should be exposed to the template without referencing the attributes hash

For example:

`<h1><%= foo %></h1>`

Instead of:

`<h1><%= attributes[:foo] %></h1>`

Note: this vote doesn't dictate how we expose to the template

**Comment by shanebo** [comment]
**Vote**: attributes keys should not be exposed to the template. That is, you have to access them through the attributes hash

For example:

`<h1><%= attributes[:foo] %></h1>`

Instead of:

`<h1><%= foo %></h1>`

**Comment by shanebo** [comment]
Alright, well should we move forward?

**Comment by joeosburn-desiringgod** [comment]
Yes. It seems to me that the next question is whether or not attributes are exposed automatically, or whether they get exposed via some helper method, i.e. the `attribute` helper.

**Comment by shanebo** [comment]
@joeosburn-desiringgod automatically is most consistent with view rendering layers in frameworks that I'm familiar with.

**Comment by joeosburn-desiringgod** [comment]
@shanebo I'm good with that. @scottcorgan @benhutton?

**Comment by scottcorgan** [comment]
I’m good with anything

**Comment by benhutton** [comment]
go for it @joeosburn-desiringgod
